### ISSUE TITLE
`Remote is not activated on this hyperdeck`

### ISSUE THREAD

**Issue by hrueger** [baltedewit/hyperdeck-server-connection#18]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi @baltedewit 
Thanks for this library, it looks really cool. I'd like to use it but unfurtunately I can't get my Atem Mini Pro to connect to it.
The Atem Software Control always shows `Remote is not activated on this HyperDeck`. I'm using the latest Atem Software Control Version v8.6.1.

Do you have any idea?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by baltedewit** [comment]
You need to add the callback for the remote message from the atem.

```
this.hyperdeck.onRemote = async (cmd) => {
	return {
		enabled: true,
		override: true
	}
}
```

**Comment by hrueger** [comment]
@baltedewit Thanks for the quick response! However, it's still not working.
Here's my complete code:
```TypeScript
import { HyperdeckServer } from "hyperdeck-server-connection";

const server = new HyperdeckServer();

server.onRemote = async (cmd) => {
    console.log(cmd);
    return {
        enabled: true,
        override: true
    } as any;
}
```
I had to use `as any` because TS expects a promise. I also tried 
```TypeScript
import { HyperdeckServer } from "hyperdeck-server-connection";

const server = new HyperdeckServer();

server.onRemote = async (cmd) => {
    console.log(cmd);
    return new Promise((resolve) => {
        resolve({
            enabled: true,
            override: true
        });
    }) as any;
}
```
But it doesn't work either. Interestingly, nothing is logged by the `console.log` command. So it seems like this method is never called.

Here's a screenshot of my Atem Interface (it's in German):
![grafik](https://user-images.githubusercontent.com/18656830/119453285-8bb9e980-bd37-11eb-9ca7-2328a8c6c919.png)

**Comment by hrueger** [comment]
The IP is definitely correct, because if I insert another IP, I get a red error message saying `Connection failed.`

**Comment by hrueger** [comment]
If I add a `console.log("received command", cmd);` after [this line](https://github.com/baltedewit/hyperdeck-server-connection/blob/2dd3d30ae7a2725f99bceb65960cc93ecefa9a18/src/server.ts#L85), I see the following to commands from the ATEM in my terminal:
```JS
received command {
  raw: 'notify: transport: true slot: true remote: true configuration: false',
  name: 'notify',
  parameters: {
    transport: 'true',
    slot: 'true',
    remote: 'true',
    configuration: 'false'
  }
}
received command { raw: 'transport info', name: 'transport info', parameters: {} }
```
They appear like every two seconds or so.

**Comment by baltedewit** [comment]
I guess that if you don't have the callback for the transport info added the Atem will display that as remote disabled (even though it is enabled). I don't remember the minimum list of callbacks required but these are the ones I use for my integration with the Atem:

```
onDeviceInfo
onPlay
onStop
onGoTo
onDiskList
onClipsGet
onTransportInfo
onRemote
onClipsCount
onSlotInfo
```

**Comment by hrueger** [comment]
Now it's working! Thanks a lot 👍
