### ISSUE TITLE
Bug / feature Request : Add the GOTO command

### ISSUE THREAD

**Issue by SNRSE** [baltedewit/hyperdeck-server-connection#5]
I'm submitting a ...
[x] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary
Hey i currently use the libary : Hyperdeck server connection.
I am missing the Command Goto(n) where n is the clip id  which is used to select which clip should be played.
i tried to add it myself but failed. Please help me

**Comment by SNRSE** [comment]
OR could you point me in the direction to add it myself please ?

**Comment by baltedewit** [comment]
Hi,

Steps to do this are as follow I think (I'm not sure when I'll have time to get to this so I'll write it out for you)

Add deserialized interface here: https://github.com/baltedewit/hyperdeck-server-connection/blob/master/src/types/DeserializedCommands.ts
Add callback in here: https://github.com/baltedewit/hyperdeck-server-connection/blob/master/src/server.ts#L20
Add if statement to call that callback in here: https://github.com/baltedewit/hyperdeck-server-connection/blob/master/src/server.ts#L91

Parameters from the remote connection should already be parsed correctly, as they are defined here: https://github.com/baltedewit/hyperdeck-server-connection/blob/master/src/types.ts#L157

Please note I have not looked at any actual output from the hyperdeck so depending on that it may or may require further work. Hope this helps!

**Comment by SNRSE** [comment]
when i run yarn build it failes and vscode displays lots of errors do i need to clone into node_modules ? 
sorry i just started using node etc

**Comment by baltedewit** [comment]
Can you try to install version "0.0.4-nightly-feat-gotoCommand-20200604-153336-1ee166e.0"? That should have the goto command added.

**Comment by SNRSE** [comment]
how do i install it ? via npm ? i tried cloning it and then run yarn build but it failed

**Comment by SNRSE** [comment]
it works :) thanks alot
